Fixed check to detect issues with MDS daemons - no up:active or not e…
tuenti/sensu-community-plugins pull request #27
Opened 2018-01-26 18:26 UTC by mrodm

Currently, check for ceph MDS daemons are not considering some states that indicate something is happening.

This PR adds to the check the detection of mds cluster degraded. For instance:
```
$ ceph health 
HEALTH_WARN mds cluster is degraded
```
Furthermore, it also fixes how MDS daemons are checked in order to see whether or not there are issues using the output of `ceph mds stat` command:
 - If there is less than ACTIVE (new config parameter) MDS daemons in `up:active` state, it should trigger a Critical
 - All standby MDS daemons are retrieved (`up:standby` state), and depending on WARN and CRIT levels , it will be trigger the right level.

2018-01-27 14:05 UTC, jsoriano requested changes

2018-01-27 14:05 UTC, jsoriano commented on plugins/ceph/check-ceph-mds.rb
> +       critical_message += run_cmd('ceph health detail')
No need to run the command again, right?
```
critical_message += message_health
```

2018-01-27 15:53 UTC, mrodm commented on plugins/ceph/check-ceph-mds.rb
> +       critical_message += run_cmd('ceph health detail')
True, not needed to run it twice. I'll update it the PR as you mention.

2018-01-27 18:11 UTC, jsoriano approved these changes

2018-01-30 10:51 UTC, AlbertoGarciaFdez approved these changes

2018-01-30 19:07 UTC, jsoriano commented on plugins/ceph/check-ceph-mds.rb
> +        warning_message  += "#{base_message} the number of standby MDS daemons running is less than or equal to #{config[:warn]}\n"
👍

2018-01-30 19:08 UTC, jsoriano commented
LGTM

2018-01-31 08:45 UTC, merged